schemas:
  car:
    name:
      type: String
      required: true
  user:
    name:
      type: String
      required: true
    age:
      type: Number
      required: true
    position:
      type: String
      default: junior
      enum:
        - junior
        - mid-level
        - senior
resolvers: main_resolvers.js
authentication: authentication.js
config:
  port: 5000
  mongoURI: 'mongodb://127.0.0.1:27017/sampleMe'
